# Generated by Django 3.1.2 on 2020-10-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissioner',
            name='password',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='пароль'),
        ),
        migrations.AddField(
            model_name='dispatcher',
            name='password',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='пароль'),
        ),
    ]
