# Generated by Django 3.1.2 on 2020-10-28 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201027_1401'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commissioner',
            options={'verbose_name': 'аварийный комиссар', 'verbose_name_plural': 'аварийные комиссары'},
        ),
    ]
