# Generated by Django 3.1.2 on 2020-10-26 19:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('road', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationByCommissioner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('new', 'новая'), ('sent', 'отправлена'), ('in_work', 'в работе'), ('decision', 'принято решение')], default='new', max_length=25, verbose_name='статус')),
                ('number', models.CharField(blank=True, help_text='создается автоматически после создания', max_length=20, verbose_name='номер заявки')),
                ('need_ambulance', models.BooleanField(default=False, verbose_name='нужна скорая?')),
                ('need_police', models.BooleanField(default=False, verbose_name='нужна полиция?')),
                ('need_mchs', models.BooleanField(default=False, verbose_name='нужен мчс?')),
                ('need_tow_truck', models.BooleanField(default=False, verbose_name='нужен эвакуатор?')),
                ('comment', models.TextField(blank=True, verbose_name='комментарий')),
            ],
            options={
                'verbose_name': 'заявка от комиссара',
                'verbose_name_plural': 'заявки от комиссаров',
            },
        ),
        migrations.CreateModel(
            name='RefusalOfApplicationByDispatcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True, verbose_name='комментарий')),
                ('commissioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.commissioner', verbose_name='комиссар')),
            ],
            options={
                'verbose_name': 'отказ от заявки',
                'verbose_name_plural': 'отказы от заявок',
            },
        ),
        migrations.CreateModel(
            name='PhotoForApplicationByCommissioner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='photo/%Y/%m/%d/', verbose_name='изображение')),
                ('application_by_commissioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.applicationbycommissioner')),
            ],
            options={
                'verbose_name': 'фото к заявлению',
                'verbose_name_plural': 'фото к заявлениям',
            },
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('called_ambulance', models.BooleanField(default=False, verbose_name='вызвана скорая?')),
                ('called_police', models.BooleanField(default=False, verbose_name='вызвана полиция?')),
                ('called_mchs', models.BooleanField(default=False, verbose_name='вызван мчс?')),
                ('called_tow_truck', models.BooleanField(default=False, verbose_name='вызван эвакуатор?')),
                ('comment', models.TextField(blank=True, verbose_name='комментарий')),
                ('application_by_commissioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.applicationbycommissioner', verbose_name='заявка')),
                ('dispatcher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.dispatcher', verbose_name='диспетчер')),
            ],
            options={
                'verbose_name': 'решение по заявке',
                'verbose_name_plural': 'решения по заявкам',
            },
        ),
        migrations.CreateModel(
            name='ApplicationByDispatcher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(blank=True, help_text='создается автоматически после создания', max_length=20, verbose_name='номер заявки')),
                ('status', models.CharField(choices=[('new', 'новая'), ('sent', 'отправлена'), ('returned', 'возвращена'), ('accepted', 'принята')], default='new', max_length=25, verbose_name='статус')),
                ('comment', models.TextField(blank=True, verbose_name='комментарий диспетчера')),
                ('came_from_user', models.BooleanField(default=False, verbose_name='заявка от пользователя')),
                ('commissioner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.commissioner', verbose_name='дорожный комиссар')),
                ('point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='road.point', verbose_name='точка')),
            ],
            options={
                'verbose_name': 'заявка от диспетчера',
                'verbose_name_plural': 'заявки от диспетчеров',
            },
        ),
        migrations.AddField(
            model_name='applicationbycommissioner',
            name='application_by_dispatcher',
            field=models.ForeignKey(blank=True, help_text='указывается если заявка пришла от диспетчека', null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.applicationbydispatcher', verbose_name='заявка от диспетчера'),
        ),
        migrations.AddField(
            model_name='applicationbycommissioner',
            name='commissioner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.commissioner', verbose_name='комиссар'),
        ),
        migrations.AddField(
            model_name='applicationbycommissioner',
            name='point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='road.point', verbose_name='точка'),
        ),
    ]
