# Generated by Django 3.1.2 on 2020-10-27 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201027_1401'),
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationbydispatcher',
            name='dispatcher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.dispatcher', verbose_name='диспетчер'),
        ),
    ]
