# Generated by Django 3.1.2 on 2020-10-27 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_applicationbydispatcher_dispatcher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationbydispatcher',
            old_name='came_from_user',
            new_name='come_from_user',
        ),
    ]
