# Generated by Django 3.1.2 on 2020-10-28 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20201027_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='refusalofapplicationbydispatcher',
            name='application_by_dispatcher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.applicationbydispatcher', verbose_name='заявка от диспетчера'),
        ),
    ]
