# Generated by Django 3.1.2 on 2020-10-28 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201027_1401'),
        ('application', '0004_refusalofapplicationbydispatcher_application_by_dispatcher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refusalofapplicationbydispatcher',
            name='commissioner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.commissioner', verbose_name='комиссар'),
        ),
    ]
