# Generated by Django 3.1.2 on 2020-10-28 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20201028_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationbycommissioner',
            name='location',
            field=models.IntegerField(blank=True, null=True, verbose_name='локация'),
        ),
        migrations.AddField(
            model_name='applicationbydispatcher',
            name='location',
            field=models.IntegerField(blank=True, null=True, verbose_name='локация'),
        ),
    ]
