# Generated by Django 3.1.2 on 2020-11-01 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_auto_20201028_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationbycommissioner',
            name='status',
            field=models.CharField(choices=[('new', 'новая'), ('sent', 'отправлена'), ('in_work', 'в работе'), ('decision', 'принято решение'), ('service_provided', 'услуга оказана')], default='new', max_length=25, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='applicationbydispatcher',
            name='status',
            field=models.CharField(choices=[('new', 'новая'), ('sent', 'отправлена'), ('returned', 'возвращена'), ('accepted', 'принята'), ('app_by_com_created', 'создана заявка комиссаром')], default='new', max_length=25, verbose_name='статус'),
        ),
    ]
