# Generated by Django 3.1.2 on 2020-10-23 13:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
            ],
            options={
                'verbose_name': 'трасса',
                'verbose_name_plural': 'трассы',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=150, verbose_name='название секции')),
                ('road', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='road.road', verbose_name='трасса')),
            ],
            options={
                'verbose_name': 'секция',
                'verbose_name_plural': 'секции',
            },
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=150, verbose_name='название точки')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='road.section', verbose_name='секция')),
            ],
            options={
                'verbose_name': 'точка',
                'verbose_name_plural': 'точки',
            },
        ),
    ]
